// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddTaskTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addTaskTest() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(948, 691));
    driver.findElement(By.id("new-task")).click();
    driver.findElement(By.id("new-task")).sendKeys("DAA assignments");
    driver.findElement(By.id("add-task")).click();
    driver.findElement(By.cssSelector("span")).click();
    driver.findElement(By.cssSelector("span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("span"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("li")).click();
    driver.findElement(By.cssSelector("span")).click();
    driver.findElement(By.cssSelector(".delete-btn")).click();
    driver.findElement(By.id("new-task")).click();
    driver.findElement(By.id("new-task")).sendKeys("ML maunual");
    driver.findElement(By.id("add-task")).click();
    driver.findElement(By.id("new-task")).click();
    driver.findElement(By.id("new-task")).sendKeys("STQA project");
    driver.findElement(By.id("add-task")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) > span")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) > .delete-btn")).click();
    driver.findElement(By.cssSelector("span")).click();
    driver.findElement(By.cssSelector(".delete-btn")).click();
  }
}
